services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: zoolan_vetmgmt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
