services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: petcare_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - petcare_db:/var/lib/postgresql/data

volumes:
  petcare_db:
