services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: petcare_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - petcare-network

  app:
    image: cristiandelahooz/petcare:latest
    ports:
      - "80:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=petcare_db
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - petcare-network

volumes:
  postgres_data:

networks:
  petcare-network:
    driver: bridge