server:
  port: ${PORT:8080}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.atmosphere: warn

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.wornux
  bun:
    enable: true
