server:
  port: ${PORT:8080}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
application:
  version: 0.0.1-SNAPSHOT

spring:
  datasource:
    password: ${DB_PASSWORD:admin}
    username: ${DB_USER:admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:petcare_db}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: [ classpath:db/migration/prod, classpath:db/migration/dev ] #, filesystem:./sql
    placeholderReplacement: false

  jpa:
    show-sql: false
    properties:
      org:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          envers:
            audit_table_suffix: _log
            store_data_at_delete: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.atmosphere: warn

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: false
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.wornux
  pnpm:
    enable: true
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true

  devtools:
    restart:
      enabled: true  # Set to enable hot deployment
      additional-paths: src/main/java # restart directory
      quiet-period: 1s
      poll-interval: 2s
      log-condition-evaluation-delta: false
---
spring:
  config:
    activate:
      on-profile: create-schema
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata
    hibernate:
      ddl-auto: create
    show-sql: false