--  ███████╗████████╗██████╗ ██╗   ██╗ ██████╗████████╗██╗   ██╗██████╗ ███████╗
--  ██╔════╝╚══██╔══╝██╔══██╗██║   ██║██╔════╝╚══██╔══╝██║   ██║██╔══██╗██╔════╝
--  ███████╗   ██║   ██████╔╝██║   ██║██║        ██║   ██║   ██║██████╔╝█████╗
--  ╚════██║   ██║   ██╔══██╗██║   ██║██║        ██║   ██║   ██║██╔══██╗██╔══╝
--  ███████║   ██║   ██║  ██║╚██████╔╝╚██████╗   ██║   ╚██████╔╝██║  ██║███████╗
--  ╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝  ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝


CREATE TABLE appointments
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_appointment_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_appointment_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    service_type           VARCHAR(255)                            NOT NULL,
    status                 VARCHAR(255)                            NOT NULL,
    reason                 VARCHAR(500),
    notes                  VARCHAR(1000),
    client_id              BIGINT,
    pet_id                 BIGINT,
    employee_id            BIGINT,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    created_by             VARCHAR(255),
    updated_by             VARCHAR(255),
    guest_client_name      VARCHAR(100),
    guest_client_phone     VARCHAR(15),
    guest_client_email     VARCHAR(100),
    CONSTRAINT pk_appointments PRIMARY KEY (id)
);

CREATE TABLE client
(
    client_id                BIGINT NOT NULL,
    cedula                   CHAR(11),
    passport                 CHAR(9),
    rnc                      CHAR(9),
    company_name             VARCHAR(255),
    preferred_contact_method VARCHAR(255),
    emergency_contact_name   VARCHAR(255),
    emergency_contact_number VARCHAR(255),
    rating                   VARCHAR(255),
    credit_limit             DOUBLE PRECISION,
    current_balance          DOUBLE PRECISION,
    payment_terms_days       INTEGER,
    notes                    VARCHAR(1000),
    reference_source         VARCHAR(255),
    verified                 BOOLEAN,
    CONSTRAINT pk_client PRIMARY KEY (client_id)
);

CREATE TABLE consultations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notes              TEXT                                    NOT NULL,
    diagnosis          TEXT,
    treatment          TEXT,
    prescription       TEXT,
    consultation_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    pet_id             BIGINT                                  NOT NULL,
    veterinarian_id    BIGINT                                  NOT NULL,
    medical_history_id BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    active             BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_consultations PRIMARY KEY (id)
);

CREATE TABLE employee
(
    employee_id             BIGINT NOT NULL,
    employee_role           VARCHAR(255),
    salary                  DOUBLE PRECISION,
    hire_date               date   NOT NULL,
    available               BOOLEAN,
    work_schedule           VARCHAR(255),
    emergency_contact_name  VARCHAR(255),
    emergency_contact_phone VARCHAR(255),
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);

CREATE TABLE medical_histories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id             BIGINT,
    allergies          TEXT,
    medications        TEXT,
    vaccinations       TEXT,
    surgeries          TEXT,
    chronic_conditions TEXT,
    notes              TEXT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    active             BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_medical_histories PRIMARY KEY (id)
);

CREATE TABLE pet_owners
(
    client_id BIGINT NOT NULL,
    pet_id    BIGINT NOT NULL
);

CREATE TABLE pets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    type       VARCHAR(255),
    breed      VARCHAR(255),
    birth_date date,
    gender     VARCHAR(255),
    active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE users
(
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username            VARCHAR(50),
    password            VARCHAR(255),
    email               VARCHAR(255),
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    phone_number        VARCHAR(255),
    birth_date          date,
    gender              VARCHAR(255),
    nationality         VARCHAR(255),
    province            VARCHAR(255)                            NOT NULL,
    municipality        VARCHAR(255)                            NOT NULL,
    sector              VARCHAR(255)                            NOT NULL,
    street_address      VARCHAR(255)                            NOT NULL,
    reference_points    VARCHAR(500),
    profile_picture_url VARCHAR(255),
    active              BOOLEAN,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    system_role         VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE waiting_room
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id               BIGINT                                  NOT NULL,
    pet_id                  BIGINT                                  NOT NULL,
    arrival_time            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status                  VARCHAR(255)                            NOT NULL,
    reason_for_visit        VARCHAR(255),
    priority                VARCHAR(255)                            NOT NULL,
    notes                   VARCHAR(255),
    consultation_started_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_waiting_room PRIMARY KEY (id)
);

ALTER TABLE client
    ADD CONSTRAINT uc_client_cedula UNIQUE (cedula);

ALTER TABLE client
    ADD CONSTRAINT uc_client_passport UNIQUE (passport);

ALTER TABLE client
    ADD CONSTRAINT uc_client_rnc UNIQUE (rnc);

ALTER TABLE medical_histories
    ADD CONSTRAINT uc_medical_histories_pet UNIQUE (pet_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (client_id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (employee_id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES users (user_id);

ALTER TABLE consultations
    ADD CONSTRAINT FK_CONSULTATIONS_ON_MEDICAL_HISTORY FOREIGN KEY (medical_history_id) REFERENCES medical_histories (id);

ALTER TABLE consultations
    ADD CONSTRAINT FK_CONSULTATIONS_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE consultations
    ADD CONSTRAINT FK_CONSULTATIONS_ON_VETERINARIAN FOREIGN KEY (veterinarian_id) REFERENCES employee (employee_id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES users (user_id);

ALTER TABLE medical_histories
    ADD CONSTRAINT FK_MEDICAL_HISTORIES_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE waiting_room
    ADD CONSTRAINT FK_WAITING_ROOM_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (client_id);

ALTER TABLE waiting_room
    ADD CONSTRAINT FK_WAITING_ROOM_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE pet_owners
    ADD CONSTRAINT fk_petown_on_client FOREIGN KEY (client_id) REFERENCES client (client_id);

ALTER TABLE pet_owners
    ADD CONSTRAINT fk_petown_on_pet FOREIGN KEY (pet_id) REFERENCES pets (id);