--  ███████╗████████╗██████╗ ██╗   ██╗ ██████╗████████╗██╗   ██╗██████╗ ███████╗
--  ██╔════╝╚══██╔══╝██╔══██╗██║   ██║██╔════╝╚══██╔══╝██║   ██║██╔══██╗██╔════╝
--  ███████╗   ██║   ██████╔╝██║   ██║██║        ██║   ██║   ██║██████╔╝█████╗
--  ╚════██║   ██║   ██╔══██╗██║   ██║██║        ██║   ██║   ██║██╔══██╗██╔══╝
--  ███████║   ██║   ██║  ██║╚██████╔╝╚██████╗   ██║   ╚██████╔╝██║  ██║███████╗
--  ╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝  ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝

CREATE SEQUENCE IF NOT EXISTS revision_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE appointments
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_appointment_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_appointment_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    service_type           VARCHAR(255)                            NOT NULL,
    status                 VARCHAR(255)                            NOT NULL,
    reason                 VARCHAR(500),
    notes                  VARCHAR(1000),
    client_id              BIGINT,
    pet_id                 BIGINT,
    employee_id            BIGINT,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    created_by             VARCHAR(255),
    updated_by             VARCHAR(255),
    guest_client_name      VARCHAR(100),
    guest_client_phone     VARCHAR(15),
    guest_client_email     VARCHAR(100),
    CONSTRAINT pk_appointments PRIMARY KEY (id)
);

CREATE TABLE appointments_log
(
    rev                        INTEGER NOT NULL,
    revtype                    SMALLINT,
    id                         BIGINT  NOT NULL,
    start_appointment_date     TIMESTAMP WITHOUT TIME ZONE,
    start_appointment_date_mod BOOLEAN,
    end_appointment_date       TIMESTAMP WITHOUT TIME ZONE,
    end_appointment_date_mod   BOOLEAN,
    service_type               VARCHAR(255),
    service_type_mod           BOOLEAN,
    status                     VARCHAR(255),
    status_mod                 BOOLEAN,
    reason                     VARCHAR(500),
    reason_mod                 BOOLEAN,
    notes                      VARCHAR(1000),
    notes_mod                  BOOLEAN,
    client_id                  BIGINT,
    client_id_mod              BOOLEAN,
    pet_id                     BIGINT,
    pet_id_mod                 BOOLEAN,
    employee_id                BIGINT,
    employee_id_mod            BOOLEAN,
    guest_client_info_mod      BOOLEAN,
    created_at                 TIMESTAMP WITHOUT TIME ZONE,
    created_at_mod             BOOLEAN,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE,
    updated_at_mod             BOOLEAN,
    created_by                 VARCHAR(255),
    created_by_mod             BOOLEAN,
    updated_by                 VARCHAR(255),
    updated_by_mod             BOOLEAN,
    guest_client_name          VARCHAR(255),
    guest_client_phone         VARCHAR(255),
    guest_client_email         VARCHAR(255),
    CONSTRAINT pk_appointments_log PRIMARY KEY (rev, id)
);

CREATE TABLE client
(
    client_id                BIGINT NOT NULL,
    cedula                   CHAR(11),
    passport                 CHAR(9),
    rnc                      CHAR(11),
    company_name             VARCHAR(255),
    preferred_contact_method VARCHAR(255),
    emergency_contact_name   VARCHAR(255),
    emergency_contact_number VARCHAR(255),
    rating                   VARCHAR(255),
    credit_limit             DOUBLE PRECISION,
    current_balance          DOUBLE PRECISION,
    payment_terms_days       INTEGER,
    notes                    VARCHAR(1000),
    reference_source         VARCHAR(255),
    verified                 BOOLEAN,
    CONSTRAINT pk_client PRIMARY KEY (client_id)
);

CREATE TABLE client_log
(
    rev                          INTEGER NOT NULL,
    client_id                    BIGINT  NOT NULL,
    cedula                       CHAR(11),
    cedula_mod                   BOOLEAN,
    passport                     CHAR(9),
    passport_mod                 BOOLEAN,
    rnc                          CHAR(11),
    rnc_mod                      BOOLEAN,
    company_name                 VARCHAR(255),
    company_name_mod             BOOLEAN,
    preferred_contact_method     VARCHAR(255),
    preferred_contact_method_mod BOOLEAN,
    emergency_contact_name       VARCHAR(255),
    emergency_contact_name_mod   BOOLEAN,
    emergency_contact_number     VARCHAR(255),
    emergency_contact_number_mod BOOLEAN,
    rating                       VARCHAR(255),
    rating_mod                   BOOLEAN,
    credit_limit                 DOUBLE PRECISION,
    credit_limit_mod             BOOLEAN,
    current_balance              DOUBLE PRECISION,
    current_balance_mod          BOOLEAN,
    payment_terms_days           INTEGER,
    payment_terms_days_mod       BOOLEAN,
    notes                        VARCHAR(1000),
    notes_mod                    BOOLEAN,
    reference_source             VARCHAR(255),
    reference_source_mod         BOOLEAN,
    verified                     BOOLEAN,
    verified_mod                 BOOLEAN
);

CREATE TABLE consultations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notes             TEXT                                    NOT NULL,
    diagnosis         TEXT,
    treatment         TEXT,
    prescription      TEXT,
    consultation_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    pet               BIGINT                                  NOT NULL,
    veterinarian      BIGINT                                  NOT NULL,
    medical_history   BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    active            BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_consultations PRIMARY KEY (id)
);

CREATE TABLE consultations_log
(
    rev                   INTEGER NOT NULL,
    revtype               SMALLINT,
    id                    BIGINT  NOT NULL,
    notes                 TEXT,
    notes_mod             BOOLEAN,
    diagnosis             TEXT,
    diagnosis_mod         BOOLEAN,
    treatment             TEXT,
    treatment_mod         BOOLEAN,
    prescription          TEXT,
    prescription_mod      BOOLEAN,
    consultation_date     TIMESTAMP WITHOUT TIME ZONE,
    consultation_date_mod BOOLEAN,
    pet                   BIGINT,
    pet_mod               BOOLEAN,
    veterinarian          BIGINT,
    veterinarian_mod      BOOLEAN,
    medical_history       BIGINT,
    medical_history_mod   BOOLEAN,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    created_at_mod        BOOLEAN,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at_mod        BOOLEAN,
    active                BOOLEAN,
    active_mod            BOOLEAN,
    CONSTRAINT pk_consultations_log PRIMARY KEY (rev, id)
);

CREATE TABLE employee
(
    employee_id             BIGINT NOT NULL,
    employee_role           VARCHAR(255),
    salary                  DOUBLE PRECISION,
    hire_date               date   NOT NULL,
    available               BOOLEAN,
    work_schedule           VARCHAR(255),
    emergency_contact_name  VARCHAR(255),
    emergency_contact_phone VARCHAR(255),
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);

CREATE TABLE employee_log
(
    rev                         INTEGER NOT NULL,
    employee_id                 BIGINT  NOT NULL,
    employee_role               VARCHAR(255),
    employee_role_mod           BOOLEAN,
    salary                      DOUBLE PRECISION,
    salary_mod                  BOOLEAN,
    hire_date                   date,
    hire_date_mod               BOOLEAN,
    available                   BOOLEAN,
    available_mod               BOOLEAN,
    work_schedule               VARCHAR(255),
    work_schedule_mod           BOOLEAN,
    emergency_contact_name      VARCHAR(255),
    emergency_contact_name_mod  BOOLEAN,
    emergency_contact_phone     VARCHAR(255),
    emergency_contact_phone_mod BOOLEAN
);

CREATE TABLE invoice_product
(
    code               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    invoice            BIGINT                                  NOT NULL,
    product            BIGINT                                  NOT NULL,
    quantity           DOUBLE PRECISION                        NOT NULL,
    price              DECIMAL                                 NOT NULL,
    amount             DECIMAL                                 NOT NULL,
    CONSTRAINT pk_invoice_product PRIMARY KEY (code)
);

CREATE TABLE invoice_product_log
(
    rev          INTEGER NOT NULL,
    revtype      SMALLINT,
    code         BIGINT  NOT NULL,
    invoice      BIGINT,
    invoice_mod  BOOLEAN,
    product      BIGINT,
    product_mod  BOOLEAN,
    quantity     DOUBLE PRECISION,
    quantity_mod BOOLEAN,
    price        DECIMAL,
    price_mod    BOOLEAN,
    amount       DECIMAL,
    amount_mod   BOOLEAN,
    CONSTRAINT pk_invoice_product_log PRIMARY KEY (rev, code)
);

CREATE TABLE invoices
(
    code                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by          VARCHAR(255)                            NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by    VARCHAR(255)                            NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    client              BIGINT                                  NOT NULL,
    consultation        BIGINT,
    consultation_notes  VARCHAR(1000),
    issued_date         date                                    NOT NULL,
    payment_date        date                                    NOT NULL,
    sales_order         VARCHAR(100),
    status              VARCHAR(255)                            NOT NULL,
    subtotal            DECIMAL                                 NOT NULL,
    discount_percentage DECIMAL,
    discount            DECIMAL,
    tax                 DECIMAL                                 NOT NULL,
    total               DECIMAL                                 NOT NULL,
    paid_to_date        DECIMAL                                 NOT NULL,
    notes               VARCHAR(500),
    CONSTRAINT pk_invoices PRIMARY KEY (code)
);

CREATE TABLE invoices_log
(
    rev                     INTEGER NOT NULL,
    revtype                 SMALLINT,
    code                    BIGINT  NOT NULL,
    client                  BIGINT,
    client_mod              BOOLEAN,
    products_mod            BOOLEAN,
    consultation            BIGINT,
    consultation_mod        BOOLEAN,
    consultation_notes      VARCHAR(1000),
    consultation_notes_mod  BOOLEAN,
    services_mod             BOOLEAN,
    payment_details_mod     BOOLEAN,
    issued_date             date,
    issued_date_mod         BOOLEAN,
    payment_date            date,
    payment_date_mod        BOOLEAN,
    sales_order             VARCHAR(255),
    sales_order_mod         BOOLEAN,
    status                  VARCHAR(255),
    status_mod              BOOLEAN,
    subtotal                DECIMAL,
    subtotal_mod            BOOLEAN,
    discount_percentage     DECIMAL,
    discount_percentage_mod BOOLEAN,
    discount                DECIMAL,
    discount_mod            BOOLEAN,
    tax                     DECIMAL,
    tax_mod                 BOOLEAN,
    total                   DECIMAL,
    total_mod               BOOLEAN,
    paid_to_date            DECIMAL,
    paid_to_date_mod        BOOLEAN,
    notes                   VARCHAR(500),
    notes_mod               BOOLEAN,
    CONSTRAINT pk_invoices_log PRIMARY KEY (rev, code)
);

CREATE TABLE medical_histories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet                BIGINT,
    allergies          TEXT,
    medications        TEXT,
    vaccinations       TEXT,
    surgeries          TEXT,
    chronic_conditions TEXT,
    notes              TEXT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    active             BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_medical_histories PRIMARY KEY (id)
);

CREATE TABLE medical_histories_log
(
    rev                    INTEGER NOT NULL,
    revtype                SMALLINT,
    id                     BIGINT  NOT NULL,
    pet                    BIGINT,
    pet_mod                BOOLEAN,
    consultations_mod      BOOLEAN,
    allergies              TEXT,
    allergies_mod          BOOLEAN,
    medications            TEXT,
    medications_mod        BOOLEAN,
    vaccinations           TEXT,
    vaccinations_mod       BOOLEAN,
    surgeries              TEXT,
    surgeries_mod          BOOLEAN,
    chronic_conditions     TEXT,
    chronic_conditions_mod BOOLEAN,
    notes                  TEXT,
    notes_mod              BOOLEAN,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    created_at_mod         BOOLEAN,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at_mod         BOOLEAN,
    active                 BOOLEAN,
    active_mod             BOOLEAN,
    CONSTRAINT pk_medical_histories_log PRIMARY KEY (rev, id)
);

CREATE TABLE payments
(
    code               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    payment_date       date                                    NOT NULL,
    total_amount       DECIMAL                                 NOT NULL,
    method             VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    reference_number   VARCHAR(250),
    notes              VARCHAR(500),
    CONSTRAINT pk_payments PRIMARY KEY (code)
);

CREATE TABLE payments_log
(
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    code                 BIGINT  NOT NULL,
    details_mod          BOOLEAN,
    payment_date         date,
    payment_date_mod     BOOLEAN,
    total_amount         DECIMAL,
    total_amount_mod     BOOLEAN,
    method               VARCHAR(255),
    method_mod           BOOLEAN,
    status               VARCHAR(255),
    status_mod           BOOLEAN,
    reference_number     VARCHAR(255),
    reference_number_mod BOOLEAN,
    notes                VARCHAR(500),
    notes_mod            BOOLEAN,
    CONSTRAINT pk_payments_log PRIMARY KEY (rev, code)
);

CREATE TABLE payments_detail
(
    code               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    payment            BIGINT                                  NOT NULL,
    invoice            BIGINT                                  NOT NULL,
    amount             DECIMAL                                 NOT NULL,
    CONSTRAINT pk_payments_detail PRIMARY KEY (code)
);

CREATE TABLE payments_detail_log
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    code        BIGINT  NOT NULL,
    payment     BIGINT,
    payment_mod BOOLEAN,
    invoice     BIGINT,
    invoice_mod BOOLEAN,
    amount      DECIMAL,
    amount_mod  BOOLEAN,
    CONSTRAINT pk_payments_detail_log PRIMARY KEY (rev, code)
);

CREATE TABLE pet_owners
(
    owners BIGINT NOT NULL,
    pet_id BIGINT NOT NULL
);

CREATE TABLE pet_owners_log
(
    owners  BIGINT  NOT NULL,
    pet_id  BIGINT  NOT NULL,
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    CONSTRAINT pk_pet_owners_log PRIMARY KEY (owners, pet_id, rev)
);

CREATE TABLE pets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    type       VARCHAR(255),
    breed      VARCHAR(255),
    birth_date date,
    gender     VARCHAR(255),
    active     BOOLEAN                                 NOT NULL,
    color      VARCHAR(255),
    size       VARCHAR(255),
    fur_type   VARCHAR(255),
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE pets_log
(
    rev                 INTEGER NOT NULL,
    revtype             SMALLINT,
    id                  BIGINT  NOT NULL,
    name                VARCHAR(255),
    name_mod            BOOLEAN,
    type                VARCHAR(255),
    type_mod            BOOLEAN,
    breed               VARCHAR(255),
    breed_mod           BOOLEAN,
    birth_date          date,
    birth_date_mod      BOOLEAN,
    owners_mod          BOOLEAN,
    gender              VARCHAR(255),
    gender_mod          BOOLEAN,
    medical_history_mod BOOLEAN,
    active              BOOLEAN,
    active_mod          BOOLEAN,
    color               VARCHAR(255),
    color_mod           BOOLEAN,
    size                VARCHAR(255),
    size_mod            BOOLEAN,
    fur_type            VARCHAR(255),
    fur_type_mod        BOOLEAN,
    CONSTRAINT pk_pets_log PRIMARY KEY (rev, id)
);

CREATE TABLE products
(
    product_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    active           BOOLEAN                                 NOT NULL,
    purchase_price   DECIMAL(10, 2)                          NOT NULL,
    sales_price      DECIMAL(10, 2)                          NOT NULL,
    accounting_stock INTEGER                                 NOT NULL,
    available_stock  INTEGER                                 NOT NULL,
    reorder_level    INTEGER                                 NOT NULL,
    unit             VARCHAR(255)                            NOT NULL,
    usage_type       VARCHAR(255)                            NOT NULL,
    supplier         BIGINT,
    category         VARCHAR(255)                            NOT NULL,
    warehouse        BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

CREATE TABLE products_log
(
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    product_id           BIGINT  NOT NULL,
    name                 VARCHAR(255),
    name_mod             BOOLEAN,
    description          VARCHAR(255),
    description_mod      BOOLEAN,
    active               BOOLEAN,
    active_mod           BOOLEAN,
    purchase_price       DECIMAL,
    purchase_price_mod   BOOLEAN,
    sales_price          DECIMAL,
    sales_price_mod      BOOLEAN,
    accounting_stock     INTEGER,
    accounting_stock_mod BOOLEAN,
    available_stock      INTEGER,
    available_stock_mod  BOOLEAN,
    reorder_level        INTEGER,
    reorder_level_mod    BOOLEAN,
    unit                 VARCHAR(255),
    unit_mod             BOOLEAN,
    usage_type           VARCHAR(255),
    usage_type_mod       BOOLEAN,
    supplier             BIGINT,
    supplier_mod         BOOLEAN,
    category             VARCHAR(255),
    category_mod         BOOLEAN,
    warehouse            BIGINT,
    warehouse_mod        BOOLEAN,
    CONSTRAINT pk_products_log PRIMARY KEY (rev, product_id)
);

CREATE TABLE revision
(
    id            INTEGER NOT NULL,
    timestamp     BIGINT  NOT NULL,
    modifier_user VARCHAR(255),
    ip_address    VARCHAR(255),
    CONSTRAINT pk_revision PRIMARY KEY (id)
);

CREATE TABLE suppliers
(
    supplier_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rnc            CHAR(11)                                NOT NULL,
    company_name   VARCHAR(255)                            NOT NULL,
    contact_person VARCHAR(255),
    contact_phone  VARCHAR(255),
    contact_email  VARCHAR(255),
    province       VARCHAR(255)                            NOT NULL,
    municipality   VARCHAR(255)                            NOT NULL,
    sector         VARCHAR(255)                            NOT NULL,
    street_address VARCHAR(255)                            NOT NULL,
    active         BOOLEAN,
    CONSTRAINT pk_suppliers PRIMARY KEY (supplier_id)
);

CREATE TABLE suppliers_log
(
    rev                INTEGER NOT NULL,
    revtype            SMALLINT,
    supplier_id        BIGINT  NOT NULL,
    rnc                CHAR(11),
    rnc_mod            BOOLEAN,
    company_name       VARCHAR(255),
    company_name_mod   BOOLEAN,
    contact_person     VARCHAR(255),
    contact_person_mod BOOLEAN,
    contact_phone      VARCHAR(255),
    contact_phone_mod  BOOLEAN,
    contact_email      VARCHAR(255),
    contact_email_mod  BOOLEAN,
    province           VARCHAR(255),
    province_mod       BOOLEAN,
    municipality       VARCHAR(255),
    municipality_mod   BOOLEAN,
    sector             VARCHAR(255),
    sector_mod         BOOLEAN,
    street_address     VARCHAR(255),
    street_address_mod BOOLEAN,
    active             BOOLEAN,
    active_mod         BOOLEAN,
    products_mod       BOOLEAN,
    CONSTRAINT pk_suppliers_log PRIMARY KEY (rev, supplier_id)
);

CREATE TABLE tokens
(
    code          VARCHAR(255)  NOT NULL,
    username      VARCHAR(50)   NOT NULL,
    access_token  VARCHAR(9999) NOT NULL,
    refresh_token VARCHAR(9999) NOT NULL,
    invalidated   BOOLEAN       NOT NULL,
    suspended     BOOLEAN       NOT NULL,
    CONSTRAINT pk_tokens PRIMARY KEY (code)
);

CREATE TABLE users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(50),
    password         VARCHAR(255),
    email            VARCHAR(255),
    first_name       VARCHAR(255),
    last_name        VARCHAR(255),
    phone_number     VARCHAR(255),
    birth_date       date,
    gender           VARCHAR(255),
    nationality      VARCHAR(255),
    province         VARCHAR(255)                            NOT NULL,
    municipality     VARCHAR(255)                            NOT NULL,
    sector           VARCHAR(255)                            NOT NULL,
    street_address   VARCHAR(255)                            NOT NULL,
    reference_points VARCHAR(500),
    active           BOOLEAN,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    system_role      VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE users_log
(
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    user_id              BIGINT  NOT NULL,
    username             VARCHAR(255),
    username_mod         BOOLEAN,
    password             VARCHAR(255),
    password_mod         BOOLEAN,
    email                VARCHAR(255),
    email_mod            BOOLEAN,
    first_name           VARCHAR(255),
    first_name_mod       BOOLEAN,
    last_name            VARCHAR(255),
    last_name_mod        BOOLEAN,
    phone_number         VARCHAR(255),
    phone_number_mod     BOOLEAN,
    birth_date           date,
    birth_date_mod       BOOLEAN,
    gender               VARCHAR(255),
    gender_mod           BOOLEAN,
    nationality          VARCHAR(255),
    nationality_mod      BOOLEAN,
    province             VARCHAR(255),
    province_mod         BOOLEAN,
    municipality         VARCHAR(255),
    municipality_mod     BOOLEAN,
    sector               VARCHAR(255),
    sector_mod           BOOLEAN,
    street_address       VARCHAR(255),
    street_address_mod   BOOLEAN,
    reference_points     VARCHAR(500),
    reference_points_mod BOOLEAN,
    active               BOOLEAN,
    active_mod           BOOLEAN,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    created_at_mod       BOOLEAN,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at_mod       BOOLEAN,
    system_role          VARCHAR(255),
    system_role_mod      BOOLEAN,
    CONSTRAINT pk_users_log PRIMARY KEY (rev, user_id)
);

CREATE TABLE waiting_room
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client                  BIGINT                                  NOT NULL,
    pet                     BIGINT                                  NOT NULL,
    arrival_time            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status                  VARCHAR(255)                            NOT NULL,
    reason_for_visit        VARCHAR(255),
    priority                VARCHAR(255)                            NOT NULL,
    notes                   VARCHAR(255),
    consultation_started_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_waiting_room PRIMARY KEY (id)
);

CREATE TABLE waiting_room_log
(
    rev                         INTEGER NOT NULL,
    revtype                     SMALLINT,
    id                          BIGINT  NOT NULL,
    client                      BIGINT,
    client_mod                  BOOLEAN,
    pet                         BIGINT,
    pet_mod                     BOOLEAN,
    arrival_time                TIMESTAMP WITHOUT TIME ZONE,
    arrival_time_mod            BOOLEAN,
    status                      VARCHAR(255),
    status_mod                  BOOLEAN,
    reason_for_visit            VARCHAR(255),
    reason_for_visit_mod        BOOLEAN,
    priority                    VARCHAR(255),
    priority_mod                BOOLEAN,
    notes                       VARCHAR(255),
    notes_mod                   BOOLEAN,
    consultation_started_at     TIMESTAMP WITHOUT TIME ZONE,
    consultation_started_at_mod BOOLEAN,
    completed_at                TIMESTAMP WITHOUT TIME ZONE,
    completed_at_mod            BOOLEAN,
    CONSTRAINT pk_waiting_room_log PRIMARY KEY (rev, id)
);

CREATE TABLE warehouses
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(50)                             NOT NULL,
    warehouse_type     VARCHAR(255)                            NOT NULL,
    status             BOOLEAN                                 NOT NULL,
    available_for_sale BOOLEAN,
    CONSTRAINT pk_warehouses PRIMARY KEY (id)
);

CREATE TABLE warehouses_log
(
    rev                    INTEGER NOT NULL,
    revtype                SMALLINT,
    id                     BIGINT  NOT NULL,
    name                   VARCHAR(50),
    name_mod               BOOLEAN,
    warehouse_type         VARCHAR(255),
    warehouse_type_mod     BOOLEAN,
    status                 BOOLEAN,
    status_mod             BOOLEAN,
    available_for_sale     BOOLEAN,
    available_for_sale_mod BOOLEAN,
    products_mod           BOOLEAN,
    CONSTRAINT pk_warehouses_log PRIMARY KEY (rev, id)
);

-- Create services table
CREATE TABLE services
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    description      TEXT,
    service_category VARCHAR(255)                            NOT NULL,
    price            DECIMAL(10, 2)                          NOT NULL,
    active           BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_services PRIMARY KEY (id)
);

-- Create services audit table
CREATE TABLE services_log
(
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    id                   BIGINT  NOT NULL,
    name                 VARCHAR(255),
    name_mod             BOOLEAN,
    description          TEXT,
    description_mod      BOOLEAN,
    service_category     VARCHAR(255),
    service_category_mod BOOLEAN,
    price                DECIMAL(10, 2),
    price_mod            BOOLEAN,
    active               BOOLEAN,
    active_mod           BOOLEAN,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    created_at_mod       BOOLEAN,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at_mod       BOOLEAN,
    CONSTRAINT pk_services_log PRIMARY KEY (rev, id)
);

-- Create invoice_services table (linking invoices with services)
CREATE TABLE invoice_services
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invoice  BIGINT                                  NOT NULL,
    service  BIGINT                                  NOT NULL,
    quantity DOUBLE PRECISION                        NOT NULL DEFAULT 1.0,
    amount   DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_invoice_services PRIMARY KEY (id)
);

-- Create invoice_services audit table
CREATE TABLE invoice_services_log
(
    rev          INTEGER NOT NULL,
    revtype      SMALLINT,
    id           BIGINT  NOT NULL,
    invoice      BIGINT,
    invoice_mod  BOOLEAN,
    service      BIGINT,
    service_mod  BOOLEAN,
    quantity     DOUBLE PRECISION,
    quantity_mod BOOLEAN,
    amount       DECIMAL(10, 2),
    amount_mod   BOOLEAN,
    CONSTRAINT pk_invoice_services_log PRIMARY KEY (rev, id)
);


ALTER TABLE client_log
    ADD CONSTRAINT pk_client_log PRIMARY KEY (client_id, rev);

ALTER TABLE employee_log
    ADD CONSTRAINT pk_employee_log PRIMARY KEY (employee_id, rev);

ALTER TABLE client
    ADD CONSTRAINT uc_client_cedula UNIQUE (cedula);

ALTER TABLE client
    ADD CONSTRAINT uc_client_passport UNIQUE (passport);

ALTER TABLE client
    ADD CONSTRAINT uc_client_rnc UNIQUE (rnc);

ALTER TABLE medical_histories
    ADD CONSTRAINT uc_medical_histories_pet UNIQUE (pet);

ALTER TABLE suppliers
    ADD CONSTRAINT uc_suppliers_contact_email UNIQUE (contact_email);

ALTER TABLE suppliers
    ADD CONSTRAINT uc_suppliers_rnc UNIQUE (rnc);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_1409182e5b04369a3d5b5459d ON payments (payment_date);

CREATE INDEX idx_1b8afb308216b1c3792b09c7c ON payments (method);

CREATE INDEX idx_49307096f5e6afc4181293de3 ON payments (status);

CREATE INDEX idx_706d6e653dc65144342f048c0 ON invoices (issued_date);

CREATE INDEX idx_77e1c8d320c63436de9525e47 ON tokens (access_token);

CREATE INDEX idx_8a51ef7887baea1422c9a39bf ON tokens (username);

CREATE INDEX idx_da8efbd4b90cc3bb5524d18ee ON invoices (payment_date);

CREATE INDEX idx_e5b53b0d0fb3e61490fc91393 ON invoices (status);

CREATE INDEX idx_e9928a68da841455a0156907a ON tokens (refresh_token);

CREATE INDEX idx_invoice_services_invoice_id ON invoice_services (invoice);

CREATE INDEX idx_invoice_services_service_id ON invoice_services (service);

CREATE INDEX idx_services_category ON services (service_category);

CREATE INDEX idx_services_active ON services (active);

CREATE INDEX idx_invoices_consultation ON invoices (consultation);

ALTER TABLE appointments_log
    ADD CONSTRAINT FK_APPOINTMENTS_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (client_id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (employee_id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE client_log
    ADD CONSTRAINT FK_CLIENT_log_ON_CLIDRE FOREIGN KEY (client_id, rev) REFERENCES users_log (user_id, rev);

ALTER TABLE client
    ADD CONSTRAINT FK_CLIENT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES users (user_id);

ALTER TABLE consultations_log
    ADD CONSTRAINT FK_CONSULTATIONS_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE consultations
    ADD CONSTRAINT FK_CONSULTATIONS_ON_MEDICAL_HISTORY FOREIGN KEY (medical_history) REFERENCES medical_histories (id);

ALTER TABLE consultations
    ADD CONSTRAINT FK_CONSULTATIONS_ON_PET FOREIGN KEY (pet) REFERENCES pets (id);

ALTER TABLE consultations
    ADD CONSTRAINT FK_CONSULTATIONS_ON_VETERINARIAN FOREIGN KEY (veterinarian) REFERENCES employee (employee_id);

ALTER TABLE employee_log
    ADD CONSTRAINT FK_EMPLOYEE_log_ON_EMIDRE FOREIGN KEY (employee_id, rev) REFERENCES users_log (user_id, rev);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES users (user_id);

ALTER TABLE invoices_log
    ADD CONSTRAINT FK_INVOICES_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_CLIENT FOREIGN KEY (client) REFERENCES client (client_id);

ALTER TABLE invoice_product_log
    ADD CONSTRAINT FK_INVOICE_PRODUCT_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE invoice_product
    ADD CONSTRAINT FK_INVOICE_PRODUCT_ON_INVOICE FOREIGN KEY (invoice) REFERENCES invoices (code);

ALTER TABLE invoice_product
    ADD CONSTRAINT FK_INVOICE_PRODUCT_ON_PRODUCT FOREIGN KEY (product) REFERENCES products (product_id);

ALTER TABLE medical_histories_log
    ADD CONSTRAINT FK_MEDICAL_HISTORIES_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE medical_histories
    ADD CONSTRAINT FK_MEDICAL_HISTORIES_ON_PET FOREIGN KEY (pet) REFERENCES pets (id);

ALTER TABLE payments_log
    ADD CONSTRAINT FK_PAYMENTS_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE payments_detail_log
    ADD CONSTRAINT FK_PAYMENTS_DETAIL_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE payments_detail
    ADD CONSTRAINT FK_PAYMENTS_DETAIL_ON_INVOICE FOREIGN KEY (invoice) REFERENCES invoices (code);

ALTER TABLE payments_detail
    ADD CONSTRAINT FK_PAYMENTS_DETAIL_ON_PAYMENT FOREIGN KEY (payment) REFERENCES payments (code);

ALTER TABLE pets_log
    ADD CONSTRAINT FK_PETS_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE products_log
    ADD CONSTRAINT FK_PRODUCTS_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_SUPPLIER FOREIGN KEY (supplier) REFERENCES suppliers (supplier_id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_WAREHOUSE FOREIGN KEY (warehouse) REFERENCES warehouses (id);

ALTER TABLE suppliers_log
    ADD CONSTRAINT FK_SUPPLIERS_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE users_log
    ADD CONSTRAINT FK_USERS_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE waiting_room_log
    ADD CONSTRAINT FK_WAITING_ROOM_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE waiting_room
    ADD CONSTRAINT FK_WAITING_ROOM_ON_CLIENT FOREIGN KEY (client) REFERENCES client (client_id);

ALTER TABLE waiting_room
    ADD CONSTRAINT FK_WAITING_ROOM_ON_PET FOREIGN KEY (pet) REFERENCES pets (id);

ALTER TABLE warehouses_log
    ADD CONSTRAINT FK_WAREHOUSES_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE pet_owners_log
    ADD CONSTRAINT fk_pet_owners_log_on_rev FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE pet_owners
    ADD CONSTRAINT fk_petown_on_client FOREIGN KEY (owners) REFERENCES client (client_id);

ALTER TABLE pet_owners
    ADD CONSTRAINT fk_petown_on_pet FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE services_log
    ADD CONSTRAINT FK_SERVICES_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE invoice_services_log
    ADD CONSTRAINT FK_INVOICE_SERVICES_log_ON_REV FOREIGN KEY (rev) REFERENCES revision (id);

ALTER TABLE invoice_services
    ADD CONSTRAINT FK_INVOICE_SERVICES_ON_INVOICE FOREIGN KEY (invoice) REFERENCES invoices (code);

ALTER TABLE invoice_services
    ADD CONSTRAINT FK_INVOICE_SERVICES_ON_SERVICE FOREIGN KEY (service) REFERENCES services (id);

ALTER TABLE invoices ADD CONSTRAINT FK_INVOICES_ON_CONSULTATION
    FOREIGN KEY (consultation) REFERENCES consultations (id);