import { PasswordField } from '@vaadin/react-components'
import type { PasswordFieldProps } from '@vaadin/react-components/PasswordField.js'

export const AUTO_FORM_CLIENT_FIELD_OPTIONS = {
  username: { label: 'Nombre de Usuario' },
  password: {
    renderer: ({ field }: { field: PasswordFieldProps }) => <PasswordField {...field} />,
    label: 'Contraseña',
  },
  email: { label: 'Correo Electrónico' },
  firstName: { label: 'Nombre' },
  lastName: { label: 'Apellido' },
  phoneNumber: { label: 'Número de Teléfono' },
  birthDate: { label: 'Fecha de Nacimiento' },
  gender: { label: 'Género' },
  nationality: { label: 'Nacionalidad' },
  cedula: { label: 'Cédula' },
  passport: { label: 'Pasaporte' },
  rnc: { label: 'RNC' },
  companyName: { label: 'Nombre de la Empresa' },
  preferredContactMethod: { label: 'Método de Contacto Preferido' },
  emergencyContactName: { label: 'Nombre del Contacto de Emergencia' },
  emergencyContactNumber: { label: 'Número de Contacto de Emergencia' },
  rating: { label: 'Calificación' },
  creditLimit: { label: 'Límite de Crédito' },
  paymentTermsDays: { label: 'Días de Términos de Pago' },
  notes: { label: 'Notas' },
  referenceSource: { label: 'Fuente de Referencia' },
  province: { label: 'Provincia' },
  municipality: { label: 'Municipio' },
  sector: { label: 'Sector' },
  streetAddress: { label: 'Dirección' },
  referencePoints: { label: 'Puntos de Referencia' },
}

export const AUTO_GRID_CLIENT_COLUMN_OPTIONS = {
  username: { header: 'Nombre de Usuario' },
  password: { header: 'Contraseña' },
  email: { header: 'Correo Electrónico' },
  firstName: { header: 'Nombre' },
  lastName: { header: 'Apellido' },
  phoneNumber: { header: 'Número de Teléfono' },
  birthDate: { header: 'Fecha de Nacimiento' },
  gender: { header: 'Género' },
  nationality: { header: 'Nacionalidad' },
  profilePictureUrl: { header: 'URL de Foto de Perfil' },
  active: { header: 'Activo' },
  createdAt: { header: 'Fecha de Creación' },
  updatedAt: { header: 'Fecha de Actualización' },
  role: { header: 'Rol' },
  cedula: { header: 'Cédula' },
  passport: { header: 'Pasaporte' },
  rnc: { header: 'RNC' },
  companyName: { header: 'Nombre de la Empresa' },
  preferredContactMethod: { header: 'Método de Contacto Preferido' },
  emergencyContactName: { header: 'Nombre del Contacto de Emergencia' },
  emergencyContactNumber: { header: 'Número de Contacto de Emergencia' },
  rating: { header: 'Calificación' },
  creditLimit: { header: 'Límite de Crédito' },
  currentBalance: { header: 'Balance Actual' },
  paymentTermsDays: { header: 'Días de Términos de Pago' },
  notes: { header: 'Notas' },
  referenceSource: { header: 'Fuente de Referencia' },
  province: { header: 'Provincia' },
  municipality: { header: 'Municipio' },
  sector: { header: 'Sector' },
  streetAddress: { header: 'Dirección de Calle' },
  referencePoints: { header: 'Puntos de Referencia' },
  verified: { header: 'Verificado' },
}
