import { PasswordField } from '@vaadin/react-components'

export const AUTO_GRID_EMPLOYEE_FIELD_OPTIONS = {
  username: { header: 'Nombre de Usuario' },
  password: {
    header: 'Contraseña',
    type: 'password',
  },
  email: { header: 'Correo Electrónico' },
  firstName: { header: 'Nombre' },
  lastName: { header: 'Apellido' },
  phoneNumber: { header: 'Número de Teléfono' },
  birthDate: { header: 'Fecha de Nacimiento' },
  gender: { header: 'Género' },
  nationality: { header: 'Nacionalidad' },
  employeeRole: { header: 'Rol del Empleado' },
  municipality: { header: 'Municipio' },
  province: { header: 'Provincia' },
  streetAddress: { header: 'Calle' },
  profilePicture: { header: 'Foto de perfil', type: 'string' },
  hireDate: { header: 'Fecha de Contratación' },
  salary: { header: 'Salario' },
  notes: { header: 'Notas' },
  available: { header: 'Disponible' },
  active: { header: 'Activo' },
  workSchedule: { header: 'Horario de Trabajo' },
  emergencyContactName: { header: 'Nombre del Contacto de Emergencia' },
  emergencyContactPhone: { header: 'Teléfono del Contacto de Emergencia' },
}

export const AUTO_FORM_EMPLOYEE_FIELD_OPTIONS = {
  username: { label: 'Nombre de Usuario' },
  password: {
    label: 'Contraseña',
  },
  email: { label: 'Correo Electrónico' },
  firstName: { label: 'Nombre' },
  lastName: { label: 'Apellido' },
  phoneNumber: { label: 'Número de Teléfono' },
  birthDate: { label: 'Fecha de Nacimiento' },
  gender: { label: 'Género' },
  nationality: { label: 'Nacionalidad' },
  employeeRole: { label: 'Rol del Empleado' },
  municipality: { label: 'Municipio' },
  province: { label: 'Provincia' },
  streetAddress: { label: 'Calle' },
  hireDate: { label: 'Fecha de Contratación' },
  salary: { label: 'Salario' },
  notes: { label: 'Notas' },
  available: { label: 'Disponible' },
  active: { label: 'Activo' },
  workSchedule: { label: 'Horario de Trabajo' },
  emergencyContactName: { label: 'Nombre del Contacto de Emergencia' },
  emergencyContactPhone: { label: 'Teléfono del Contacto de Emergencia' },
}
